### ISSUE TITLE
Wish: support X-Forwarded-For with multiple IPs

### ISSUE THREAD

**Issue by markstos** [bendrucker/req-ip#1]
The current solution assumes that X-Forwarded-For returns a single IP, but it may contain a comma separated list.

The best practice is to use the left-most address, as the [req-ip](https://www.npmjs.com/package/x-forwarded-for-wrangler) module implements.

**Comment by bendrucker** [comment]
Easy, can you take a look at https://github.com/bendrucker/req-ip/pull/2?

My Googling seems to suggest that these entries should be `comma+space` separated. Given that reverse proxies are going to be the ones implementing the header value I think it's safe to be strict about it as opposed to splitting on `,` and then trimming.
